#include <Arduino.h>

#define JOINT_1_STEP_PIN (2)
#define JOINT_1_DIRECTION_PIN (5)
#define JOINT_2_STEP_PIN (3)
#define JOINT_2_DIRECTION_PIN (6)
#define JOINT_3_STEP_PIN (4)
#define JOINT_3_DIRECTION_PIN (7)
#define JOINT_4_STEP_PIN (12)
#define JOINT_4_DIRECTION_PIN (13)

#define JOINT_1_LIMIT_SWITCH_PIN (9)
#define JOINT_2_LIMIT_SWITCH_PIN (11)
#define JOINT_3_LIMIT_SWITCH_PIN (A3)
#define JOINT_4_LIMIT_SWITCH_PIN (10)

#define JOINT_1_LIMIT_DIRECTION (-1)
#define JOINT_2_LIMIT_DIRECTION (-1)
#define JOINT_3_LIMIT_DIRECTION (1)
#define JOINT_4_LIMIT_DIRECTION (1)

#define JOINT_1_ANGLE_TO_STEPS (44.444444)
#define JOINT_2_DISTANCE_TO_STEPS (100)
#define JOINT_3_ANGLE_TO_STEPS (35.555555)
#define JOINT_4_ANGLE_TO_STEPS (10)

#define DEBUG (1)